### PR TITLE
costSortBtns

### PR DESCRIPTION
**Pull request by SchuylerL**
# Cost and stock sorting buttons
- The cost and stock sorting buttons are working, ascending and descending options. Buttons galore.
- Moved Google Oauth Login to userHeader. Removed cart from menuBar.
- Made updates to the text display in the single product cards.

### CODE REVIEW

**Comment by nicknapoli82** [comment]
I think we need to make a real decision at this point. Before this PR goes through. Should we leave the cart link in the MenuBar, or in the Header?
May I suggest the Header, which is why I'm making comment right now.

**Comment by SchuylerL** [comment]
yeah, cart button in the header is good. I was also thinking about the google login button. We should put that in the login form area so it disappears once someone logs in.

**Comment by nicknapoli82** [comment]
Cool man. If you would please remove the cart button from MenuBar then I'm good. 
Good work man. Keep it up!
I also agree with your thought of moving the google login button into the header. If you want to take care of that go for it.

**Comment by SchuylerL** [comment]
great. Moved Google Login to userHeader. Removed cart from menuBar. Merged with most recent dev. Pushed changes.

**Review by nicknapoli82 — APPROVED** [review]
This looks great man. Thank you!

**Pull request merged**
