### PR TITLE
classProductsBtnCSS

### PR DESCRIPTION
**Pull request by SchuylerL**
## Class Products Button 
- Created a 'Class Products' button so a user will see products filtered according to the class of the logged in user.
- CSS enhancements
- Added some components, added class property to products.json and the product model.
- Re-worked createUserForm a bit
- Made reducer and route changes

### CODE REVIEW

**Review by nicknapoli82 — COMMENTED** [review]
This feels a little brittle to me, and I think we are only beginning to observe why.

I feel the product model should not have information stored in it that does not directly pertain to the product itself. Having to extend Models to allow for different queries is not the way to go.

I had mentioned earlier the possibility of making a filters, or tags table which is a middle table explaining how different relationships work between tables. 

I feel hesitant to approve the direction this is going based on future concern.

**Comment by roboMoose** [comment]
I tend to agree with Nick on this one. I like the idea of implementing a recommendation system but it should be done using a join table, possible between user, product, and possibly the cart. This will separate the concerns better as well as be more scaleable. There are also some merge conflicts that need to be looked into. Unfortunately, these probably came up from all the recent PR's... 

I can't do anything while I'm at work, but I'll pull it down and play with it a little when I get home.

**Comment by roboMoose** [comment]
Schuyler, if possible, can you simply this pull-request (make another branch off it) that includes some of the other attributes such as the improved CSS and UI elements? We can then implement those and brain storm the recommendation system in isolation.

**Comment by SchuylerL** [comment]
The merge conflicts are that I removed a console.log in cartReducer.js, and imported a file in App.js. I think it's ok to have a recommended product class. So users don't have to look through all products.  They can just choose their class specific products and it lists their user class in the header.

**Comment by roboMoose** [comment]
Okay - lets merge it with the understanding that we may need to go back later, if time permits, and improve it. I just want to be clear - the recommendation feature will not limit a user/guest from viewing/filtering all the products just because they have a certain class, correct? This is just an option for a logged in user?

**Comment by SchuylerL** [comment]
Correct, there's a class products button. If a guest clicks that it asks for them to register/login. The guest can always choose from the other buttons like all products, etc. If a user logs in their class will display in the header and the class products button will populate with their recommended class items and they can still see all of the other buttons like all products, etc.

**Review by roboMoose — APPROVED** [review]

**Comment by roboMoose** [comment]
Let's leave this branch open for potential expansion down the road.

**Pull request merged**
