### PR TITLE
Admin user

### PR DESCRIPTION
**Pull request by roboMoose**
Fixed the detailed product bug
Added stripe to the dependencies
Put back in the create product route that went missing somewhere...

### CODE REVIEW

**Review by SamOlivas — DISMISSED** [review]
Lookin' good 😎

**Comment by roboMoose** [comment]
whoops - i kept working on the branch without realizing it. Dont merge yet - I want to finish the next feature first before merging. I'll let you know when its ready to go.

**Comment by roboMoose** [comment]
Okay PR is ready for review

A user can now edit their won user info. I tried to allow password editing but due to the hashing, this may be tricky and I get an inconsistent error originating in a hash.js file. I left the code in, but commented out, to revisit later if there is time.

**Review by nicknapoli82 — APPROVED** [review]
I feel confident in this PR. 
Thanks for adding in this feature Thom.

**Pull request merged**
